# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare script
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy rest of source and build
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files
COPY --from=builder /app/build ./build

# Copy package files to install production deps
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

# Default command for MCP stdio
ENTRYPOINT ["node", "build/index.js"]
CMD []
